name: pytest

on:
  push:

jobs:
  first-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - name: ubuntu install
      run: |
        sudo apt update -y && sudo apt upgrade -y  && \
        sudo apt install -y tzdata && \
        sudo apt install -y python3 \
        python3-pip \
        tzdata \
        libopencv-dev \
        tesseract-ocr \
        libtesseract-dev \
        tesseract-ocr-eng \
        libgl1-mesa-dev
    - name: python install
      run: pip3 install pyocr \
        Pillow \
        opencv-python \
        flask \
        openai
    - name: test
      run: |
        pytest ./src/test/ocr_test.py
        pytest ./src/test/prompt_test.py